# Generated by Django 3.0 on 2019-12-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_feature_img', models.CharField(max_length=1000)),
                ('article_title', models.CharField(max_length=1000)),
                ('article_desc', models.TextField()),
                ('article_content', models.TextField()),
                ('published_date', models.DateField()),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        ),
    ]
